import os
from building import *

cwd = GetCurrentDir()

src_dir = cwd

src = []
for root, dirs, files in os.walk(src_dir):
    for file in files:
        if file.endswith((".c", ".cpp")):
            src.append(os.path.join(root, file))


include_path = [
    cwd,
]

group = DefineGroup("nofrendo", src, depend=[""])
Return("group")
